### PR TITLE
Implemented data models, game logic, and unit tests

### PR DESCRIPTION
**Pull request by codemonkey800**
# Data Models

I created a base class for the data models. It's called `Model` (Go figure), and it defines a few useful
methods for attaching listeners and stuff. It also defines a method to commit and undo changes for the game.

There are only two models: `PitModel` and `MancalaModel`. Both hold one type of data: the amount of stones.

The way how model works is that you can modify the data using the data models, but the change listeners won't be invoked until you commit your changes, so make sure you call `commitChange()` when you want your listeners to be invoked.
# Mancala Game

The game logic is located inside the `MancalaGame` class. It's somewhat complicated I guess because I write shitty code. The game works by
storing the mancalas in their own array of length 2, and the pits in
a `2x6` array. The length 2 part corresponds to the player, so you can access the mancala of a player or row of a player via `mancalas[PLAYER_INDEX]` or `board[PLAYER_INDEX][i]`. Since we're using regular arrays, there shouldn't be any overhead.

The main logic of the game is located in `selectPit()`. I won't explain how the code works since you can read the code in the source file. Just know it works (Hopefully lol).

When implementing the controller, you'll be using the `MancalaGame` class to simulate the game flow. So say we have a class called `TestController`. You would use the `MancalaGame` class like so:

``` java
public final class TestController {
    public static void main(String[] args) {
        // Use 4 stones per pit
        MancalaGame game = new MancalaGame(MancalaGame.MAX_INITAL_STONES);

        // Player A goes first, and selects pit A1
        game.selectPit(0);
        // Commits player A's selection, and switches
        // the control over to player B
        game.commitLastSelection();

        // Player B selects pit B4
        game.selectPit(3);
        // Player B decides to undo
        game.undoLastSelection();

        // Don't do another undo after, otherwise
        // a RuntimeException will be thrown
        // game.undoLastSelection();

        game.selectPit(2);
        // The current player is still player B
        // since he or she landed in the mancala
        // for the final stone
        System.out.pritnln(game.getCurrentPlayer());

        // Should print out -1 since no one has won yet
        System.out.println(game.getWinningPlayer());

        // Should print false since no one has won yet
        // You should always check the return value
        // of this method after each committed selection.
        // If you don't, a RuntimeException will be thrown
        // because you tried to run an operation while the game
        // was already over.
        System.out.println(game.isGameOver());
    }
}
```

I tried to make the API as simple as possible. If you want me to change anything, definitely highlight any code in this pull request before letting me merge.
# Unit Tests

I also wrote JUnit tests for the `MancalaGame` class. You can run the unit tests directly in Eclipse (I'm not sure how though). I use Gradle. I might include it later, but for now work with what you got. All the tests pass so things should be cool.
# Docs

I made the JavaDocs available through the `gh-pages` branch. You can access them here: [http://codemonkey800.github.io/fall2015-cs151-project/](http://codemonkey800.github.io/fall2015-cs151-project/).

Feel free to add more docs as you write code your code.

### CODE REVIEW

**Comment by codemonkey800** [comment]
I'll just merge the code into master lol

**Comment by AaronEscoto** [comment]
Yeah go ahead I glanced over it earlier I didn't connect the all the dots or run it yet but it looks good

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by codemonkey800** [comment]
We need to get started on the UI lol

**Comment by AaronEscoto** [comment]
Yeah sorry man got like 3 group projects and everyone wants to meet before finals


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Pull request merged**
